#!/usr/bin/env bash
# Displays "Best School" 10 times, with a "Hi" on the 9th iteration
counter=1
while [ $counter -le 10 ]
do
    echo "Best School"
    if [ $counter -eq 9 ]
    then
        echo "Hi"
    fi
    ((counter++))
done
